[project]
name = "mscl-rs"
version = "0.1.0"
description = "Parser for MicroStrain Communication Library (MSCL) packets in Rust."
readme = "README.md"
authors = [
    { name = "Harshil", email = "37377066+harshil21@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "maturin>=1.9.6",
    "msgspec>=0.19.0",
]

[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"
